# Generated by Django 5.2.6 on 2025-10-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Microblog_API', '0002_alter_post_options_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['author'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
