# Generated by Django 5.2.7 on 2025-10-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Microblog_API', '0005_alter_comment_author_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
