# Generated by Django 5.2.7 on 2025-10-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Microblog_API', '0009_comment_liked_by_post_likes_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='liked_by',
            new_name='likes',
        ),
    ]
