# Generated by Django 5.2.7 on 2025-10-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Microblog_API', '0010_rename_liked_by_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
